pub const REMOTE_SERVER_HOST: &str = "dev-tools-rust.vercel.app";

pub const MEDIA_TYPES: [(&str, &str); 4] = [
    ("application/xml", "xml"),
    ("application/json", "json"),
    ("text/html", "html"),
    ("text/xml", "xml"),
];

pub const HEADERS_AUTOCOMPLETE: [&str; 57] = [
//    "Accept",
    "Accept-Charset",
    "Accept-Encoding",
//    "Accept-Language",
    "Accept-Patch",
    "Accept-Ranges",
    "Access-Control-Allow-Credentials",
    "Access-Control-Allow-Headers",
    "Access-Control-Allow-Methods",
    "Access-Control-Allow-Origin",
    "Access-Control-Expose-Headers",
    "Access-Control-Max-Age",
    "Access-Control-Request-Headers",
    "Access-Control-Request-Method",
    "Age",
    "Allow",
    "Authorization",
    "Cache-Control",
    "Connection",
    "Content-Encoding",
    "Content-Disposition",
    "Content-Language",
    "Content-Length",
    "Content-Location",
    "Content-Range",
//    "Content-Type",
    "Cookie",
    "Date",
    "ETag",
    "Expect",
    "Expires",
    "From",
    "Host",
    "If-Match",
    "If-Modified-Since",
    "If-None-Match",
    "If-Range",
    "If-Unmodified-Since",
    "Last-Modified",
    "Link",
    "Location",
    "Max-Forwards",
    "Origin",
    "Pragma",
    "Proxy-Authenticate",
    "Proxy-Authorization",
    "Range",
    "Referer",
    "Retry-After",
    "Server",
    "Set-Cookie",
    "Set-Cookie2",
    "TE",
    "Trailer",
    "Transfer-Encoding",
    "Upgrade",
//    "User-Agent",
    "Vary",
    "Via",
    "Warning",
    "WWW-Authenticate",
];

pub const MEDIA_TYPES_AUTOCOMPLETE: [&str; 23] = [
    "*/*",
    "application/atom+xml",
    "application/cbor",
    "application/x-www-form-urlencoded",
    "application/graphql+json",
    "application/json",
    "application/json;charset=UTF-8",
    "application/problem+json",
    "application/problem+json;charset=UTF-8",
    "application/problem+xml",
    "application/rss+xml",
    "application/x-ndjson",
    "application/stream+json",
    "application/xhtml+xml",
    "application/xml",
    "multipart/form-data",
    "multipart/mixed",
    "multipart/related",
    "text/event-stream",
    "text/html",
    "text/markdown",
    "text/plain",
    "text/xml",
];
