// a curl cli parser
ws = _{ " " | "\t" }
newline = _{ "\r" | "\n" }
slash = _{ ("\\" | "^") ~ ws* ~ newline+ }

comment = _{ "#" ~ (!newline ~ ANY)* ~ newline }

single_quoted_dollar = _{ "$" ~ "'" ~ single_quoted_inner ~ "'" }

single_quoted = _{ "'" ~ single_quoted_inner ~ "'" }
single_quoted_inner = { (!"'" ~ ANY)* }
double_quoted = _{ "\"" ~ double_quoted_inner ~ "\"" }
double_quoted_inner = { (("\\" ~ ANY) | (!"\"" ~ ANY))* }

none_ws = { (!ws ~ ANY)+ }
url_plain = @{ "http" ~ "s"? ~ "://" ~ none_ws }
url = { single_quoted | double_quoted | url_plain}
option = _{ method_option | header_option | cookie_option | data_raw_option | location_option | body_option | auth_option | ssl_verify_option | compressed_option | url_option | verbose_option | output_option | silent_option | head_option | fail_option | show_headers_option | user_agent_option }

method_option = _{ ("-X" | "--request") ~ ws+ ~ method }
method = { single_quoted | double_quoted | none_ws }

header_option = _{ ("-H" | "--header") ~ ws+ ~ header }
header = { single_quoted | double_quoted | none_ws }

cookie_option = _{ ("-b" | "--cookie") ~ ws+ ~ cookie }
cookie = { single_quoted | double_quoted | none_ws }

data_raw_option = _{ "--data-raw" ~ ws+ ~ data_raw }
data_raw = { single_quoted | double_quoted | single_quoted_dollar | (!((" -" ~ ASCII_ALPHA_UPPER) | (" --" ~ ASCII_ALPHA_LOWER) | "\\") ~ ANY)+ }

location_option = _{ ("-L" | "--location") ~ ws+ ~ location }
location = { single_quoted | double_quoted | none_ws }

body_option = _{ ("-d" | "--data") ~ ws+ ~ body }
body = { single_quoted | double_quoted | (!((" -" ~ ASCII_ALPHA_UPPER) | (" --" ~ ASCII_ALPHA_LOWER) | "\\") ~ ANY)+ }

auth_option = _{ "-u" ~ ws+ ~ auth }
auth = { single_quoted | double_quoted | none_ws }

ssl_verify_option = { ("-k" | "--insecure") }

compressed_option = { "--compressed" }

verbose_option = { ("-v" | "--verbose") }
output_option = { ("-o" | "--output") }
silent_option = { ("-s" | "--silent") }
head_option = { ("-I" | "--head") }
fail_option = { ("-f" | "--fail") }
show_headers_option = { ("-i" | "--show-headers") }

user_agent_option = _{ ("-A" | "--user-agent") ~ ws+ ~ user_agent }
user_agent = { single_quoted | double_quoted | none_ws }

url_option = { "--url" }

wss = _{ ws* ~ slash* ~ ws* }

input = _{
    SOI ~ (comment | ws | newline)* ~ ws* ~ ("curl.exe" | "curl") ~ wss ~ (option ~ wss )* ~ url? ~ (wss ~ option ~ wss)* ~ ws* ~ EOI
}
