import { EditorView, basicSetup } from "codemirror";
import { EditorState, StateEffect, Compartment } from "@codemirror/state"
import { json, jsonParseLinter } from "@codemirror/lang-json";
import { linter } from "@codemirror/lint";
import { xml } from "@codemirror/lang-xml";
import { syntaxTree } from "@codemirror/language";
import { markdown } from '@codemirror/lang-markdown'
import { html } from "@codemirror/lang-html";
import { vsCodeDark } from '@fsegurai/codemirror-theme-vscode-dark'
import { vsCodeLight } from '@fsegurai/codemirror-theme-vscode-light'

const themeCompartment = new Compartment();

function getSystemTheme() {
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? vsCodeDark : vsCodeLight;
}

function getExtensionsByLang(lang) {
    let extensions = [];
    if (lang == "xml") {
        extensions.push(markdown(), xml(), xmlLinter);
    } else if (lang == "json") {
        extensions.push(json(), linter(jsonParseLinter()));
    } else if (lang == "html") {
        extensions.push(html());
    }

    return extensions;
}

window.initCodeEditor = (elementId, initialValue, lang, readOnly, onDocChange) => {
    const parentElement = document.getElementById(elementId);

    let extensions = [
        basicSetup,
        EditorView.lineWrapping,
        EditorState.readOnly.of(readOnly),
        themeCompartment.of(getSystemTheme()),
        EditorView.updateListener.of((update) => {
            if (update.docChanged) {
                onDocChange(update.state.doc.toString());
            }
        })
    ];

    extensions.push(getExtensionsByLang(lang));

    let startState = EditorState.create({
        doc: initialValue,
        extensions: extensions
    })

    return new EditorView({
        state: startState,
        parent: parentElement
    });
};

window.setCodeEditorValue = (editorView, newValue) => {
    if (editorView) {
        editorView.dispatch({
            changes: {
                from: 0,
                to: editorView.state.doc.length,
                insert: newValue
            }
        });
    }
};


// XML

const xmlLinter = linter((view) => {
    const diagnostics = [];

    // Iterate over the parsed syntax tree nodes
    syntaxTree(view.state).cursor().iterate((node) => {
        // Check for standard XML syntax error nodes generated by the Lezer parser
        if (node.name === "MismatchedCloseTag" || node.name === "InvalidText") {
            diagnostics.push({
                from: node.from,
                to: node.to,
                severity: "error",
                message: node.name === "MismatchedCloseTag"
                    ? "Mismatched XML close tag"
                    : "Syntax error in XML structure"
            });
        }
    });

    return diagnostics;
});

// RECONFIGURE

window.codeEditorChangeLang = (editorView, lang, readOnly, onDocChange) => {
    if (editorView) {
        let extensions = [
            basicSetup,
            EditorView.lineWrapping,
            EditorState.readOnly.of(readOnly),
            themeCompartment.of(getSystemTheme()),
            EditorView.updateListener.of((update) => {
                if (update.docChanged) {
                    onDocChange(update.state.doc.toString());
                }
            })
        ];

        extensions.push(getExtensionsByLang(lang));

        editorView.dispatch({
            effects: StateEffect.reconfigure.of(extensions)
        });

    }
};


