import { EditorView, basicSetup } from "codemirror";
import { EditorState, StateEffect, Compartment  } from "@codemirror/state"
import { json, jsonParseLinter } from "@codemirror/lang-json";
import { linter } from "@codemirror/lint";
import { xml } from "@codemirror/lang-xml";
import { syntaxTree } from "@codemirror/language";
import { markdown } from '@codemirror/lang-markdown'
import { vsCodeDark } from '@fsegurai/codemirror-theme-vscode-dark'
import { vsCodeLight } from '@fsegurai/codemirror-theme-vscode-light'

var codeEditorView = null;
const themeCompartment = new Compartment();

function getSystemTheme() {
  return window.matchMedia('(prefers-color-scheme: dark)').matches ? vsCodeDark : vsCodeLight;
}

window.initCodeEditor = (elementId, initialValue, onDocChange) => {
    const parentElement = document.getElementById(elementId);

    let startState = EditorState.create({
        doc: initialValue,
        extensions: [
            basicSetup,
            EditorView.updateListener.of((update) => {
                if (update.docChanged) {
                    onDocChange(update.state.doc.toString());
                }
            })
        ]
    })

    codeEditorView = new EditorView({
        state: startState,
        parent: parentElement
    })
};

window.setCodeEditorValue = (newValue) => {
    if (codeEditorView) {
        codeEditorView.dispatch({
            changes: {
                from: 0,
                to: codeEditorView.state.doc.length,
                insert: newValue
            }
        });
    }
};


// XML

const xmlLinter = linter((view) => {
    const diagnostics = [];

    // Iterate over the parsed syntax tree nodes
    syntaxTree(view.state).cursor().iterate((node) => {
        // Check for standard XML syntax error nodes generated by the Lezer parser
        if (node.name === "MismatchedCloseTag" || node.name === "InvalidText") {
            diagnostics.push({
                from: node.from,
                to: node.to,
                severity: "error",
                message: node.name === "MismatchedCloseTag"
                    ? "Mismatched XML close tag"
                    : "Syntax error in XML structure"
            });
        }
    });

    return diagnostics;
});

// RECONFIGURE

window.codeEditorChangeLang = (lang, onDocChange) => {
    if (codeEditorView) {
        if (lang == "xml") {
            codeEditorView.dispatch({
                effects: StateEffect.reconfigure.of([
                    basicSetup,
                    markdown(),
                    themeCompartment.of(getSystemTheme()),
                    xml(),
                    xmlLinter,
                    EditorView.updateListener.of((update) => {
                        if (update.docChanged) {
                            onDocChange(update.state.doc.toString());
                        }
                    })
                ])
            });
        } else if (lang == "json") {
            codeEditorView.dispatch({
                effects: StateEffect.reconfigure.of([
                    basicSetup,
                    themeCompartment.of(getSystemTheme()),
                    json(),
                    linter(jsonParseLinter()),
                    EditorView.updateListener.of((update) => {
                        if (update.docChanged) {
                            onDocChange(update.state.doc.toString());
                        }
                    })
                ])
            });
        } else {
            codeEditorView.dispatch({
                effects: StateEffect.reconfigure.of([
                    basicSetup,
                    themeCompartment.of(getSystemTheme()),
                    EditorView.updateListener.of((update) => {
                        if (update.docChanged) {
                            onDocChange(update.state.doc.toString());
                        }
                    })
                ])
            });
        }
    }
};


